---
.travis.yml:
  secure: "ExSbFQsxOlpFTc/4TTGJElIx0/sYNZ1I2Nbd9EfGPNeECXBgmqTdJmPqdV6cl3mKDFh+tSSxnIDZe5BILhmxIR7aF2lbf8jwcbo2nxe9qAZ42GDKNV2klNXUjR7kA7tz220RNO9rM3HDKAwrKtCPtwQ0Q5u90YGGJDj2nr7NUaM="
  docker_sets:
    - set: centos7-64
    - set: centos8-64
    - set: debian9-64
    - set: debian10-64
    - set: ubuntu1604-64
    - set: ubuntu1804-64
  addons:
    apt:
      packages:
        - libaugeas-dev
